"""create the categories, courses, sections, lessons models and custom enums

Revision ID: 98240649a92d
Revises: 
Create Date: 2026-03-15 14:40:24.253789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98240649a92d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='course_levels'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='course_statuses'), server_default='DRAFT', nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_author_id', 'courses', ['author_id'], unique=False)
    op.create_index('ix_courses_category_id', 'courses', ['category_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position', name='uq_sections_course_id_position')
    )
    op.create_index('ix_sections_course_id', 'sections', ['course_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lesson_type', postgresql.ENUM('VIDEO', 'TEXT', 'QUIZ', name='lesson_types'), server_default='TEXT', nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'position', name='uq_lessons_section_id_position')
    )
    op.create_index('ix_lessons_section_id', 'lessons', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lessons_section_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_sections_course_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_courses_category_id', table_name='courses')
    op.drop_index('ix_courses_author_id', table_name='courses')
    op.drop_table('courses')
    op.drop_table('categories')
    op.execute('DROP TYPE IF EXISTS lesson_types')
    op.execute('DROP TYPE IF EXISTS course_statuses')
    op.execute('DROP TYPE IF EXISTS course_levels')
    # ### end Alembic commands ###
