"""name is unique in Category model

Revision ID: a7ec7cd80234
Revises: 98240649a92d
Create Date: 2026-03-18 16:03:10.048197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7ec7cd80234"
down_revision: Union[str, Sequence[str], None] = "98240649a92d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_categories_name", "categories", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_categories_name", "categories", type_="unique")
    # ### end Alembic commands ###
