"""create the Enrollment, CourseProgress, LessonProgress models

Revision ID: 23936f205264
Revises:
Create Date: 2026-03-29 18:29:18.467238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23936f205264"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("total_lessons", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("last_lesson_id", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "course_id", name="uq_course_progress_user_course"
        ),
    )
    op.create_index(
        "ix_course_progress_course_id", "course_progress", ["course_id"], unique=False
    )
    op.create_index(
        "ix_course_progress_user_id", "course_progress", ["user_id"], unique=False
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "COMPLETED", "DROPPED", name="enrollment_statuses"
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "enrolled_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollments_user_course"),
    )
    op.create_index(
        "ix_enrollments_course_id", "enrollments", ["course_id"], unique=False
    )
    op.create_index("ix_enrollments_user_id", "enrollments", ["user_id"], unique=False)
    op.create_table(
        "lesson_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="lesson_progress_statuses",
            ),
            server_default="NOT_STARTED",
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "lesson_id", name="uq_lesson_progress_user_lesson"
        ),
    )
    op.create_index(
        "ix_lesson_progress_course_id", "lesson_progress", ["course_id"], unique=False
    )
    op.create_index(
        "ix_lesson_progress_lesson_id", "lesson_progress", ["lesson_id"], unique=False
    )
    op.create_index(
        "ix_lesson_progress_section_id", "lesson_progress", ["section_id"], unique=False
    )
    op.create_index(
        "ix_lesson_progress_user_id", "lesson_progress", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lesson_progress_user_id", table_name="lesson_progress")
    op.drop_index("ix_lesson_progress_section_id", table_name="lesson_progress")
    op.drop_index("ix_lesson_progress_lesson_id", table_name="lesson_progress")
    op.drop_index("ix_lesson_progress_course_id", table_name="lesson_progress")
    op.drop_table("lesson_progress")
    op.drop_index("ix_enrollments_user_id", table_name="enrollments")
    op.drop_index("ix_enrollments_course_id", table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index("ix_course_progress_user_id", table_name="course_progress")
    op.drop_index("ix_course_progress_course_id", table_name="course_progress")
    op.drop_table("course_progress")
    op.execute("DROP TYPE IF EXISTS enrollment_statuses")
    op.execute("DROP TYPE IF EXISTS lesson_progress_statuses")
    # ### end Alembic commands ###
